title: Tinydew4
author: Hur jung-ju
email: tinydew4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  개인 북마크.
baseurl: "/bookmark"
url: "https://tinydew4.github.io"
github_username:  tinydew4

# Build settings
markdown: kramdown
theme: minima
